import crypto from "node:crypto";
import { prisma } from "../../config/database";
import { ApiError } from "../../shared/errors/api-error";
import type { AuthUser } from "../../shared/types/http";
import { sha256 } from "../../shared/utils/tokens";

import { emitWorkshopDomainEvent } from "../workshops/workshop.events";

import jwt from "jsonwebtoken";
import { env } from "../../config/environment";

export async function generateMyQr(user: AuthUser, sessionId: string) {
  const session = await prisma.workshopSession.findUnique({
    where: { id: sessionId },
    include: { workshop: true }
  });
  if (!session) throw new ApiError(404, "NOT_FOUND", "Session not found");

  const registration = await prisma.registration.findUnique({
    where: { workshopId_userId: { workshopId: session.workshopId, userId: user.id } }
  });

  if (!registration || registration.status !== "CONFIRMED") {
    throw new ApiError(403, "FORBIDDEN", "Your registration is not confirmed");
  }

  if (session.status !== "LIVE") {
    throw new ApiError(403, "FORBIDDEN", "Attendance has not started yet.");
  }

  // Generate 30s window timestamp
  const now = Date.now();
  const windowMs = 30 * 1000;
  const windowId = Math.floor(now / windowMs);

  const payload = {
    sessionId,
    purpose: "ATTENDANCE_CHECKIN",
    window: windowId,
  };

  const jwtToken = jwt.sign(payload, env.jwtSecret, { expiresIn: "30s" });
  
  // Passcode fallback: 6 unambiguous characters derived from HMAC
  const hmac = crypto.createHmac("sha256", env.jwtSecret);
  hmac.update(`${sessionId}:${windowId}`);
  const passcode = hmac.digest("hex").slice(0, 6).toUpperCase();

  const expiresAt = new Date((windowId + 1) * windowMs);

  return {
    sessionId,
    expiresAt: expiresAt.toISOString(),
    expiresIn: Math.max(0, Math.floor((expiresAt.getTime() - now) / 1000)),
    qrPayload: jwtToken,
    passcode
  };
}


export async function verifyMyQr(user: AuthUser, input: { sessionId: string; token: string }) {
  const session = await prisma.workshopSession.findUnique({ where: { id: input.sessionId } });
  if (!session) throw new ApiError(404, "NOT_FOUND", "Session not found");
  if (session.status !== "LIVE") throw new ApiError(403, "FORBIDDEN", "Attendance has not been started.");

  let registration = await prisma.registration.findUnique({
    where: { workshopId_userId: { workshopId: session.workshopId, userId: user.id } }
  });

  if (!registration) {
    // Seamless QR flow: auto-register the participant if they scan the QR code and are authenticated
    registration = await prisma.registration.create({
      data: {
        workshopId: session.workshopId,
        userId: user.id,
        status: "CONFIRMED",
        confirmedAt: new Date(),
      }
    });
  } else if (registration.status !== "CONFIRMED") {
    throw new ApiError(403, "FORBIDDEN", "Registration is not confirmed.");
  }

  // --- Token Verification ---
  // Priority 1: Hash-based token (issued by organizer via POST /sessions/:id/qr)
  // The organizer QR uses sha256(randomToken) stored in session.qrTokenHash.
  // This token does NOT expire — the session itself being LIVE is the gate.
  const isHashToken = !input.token.includes(".") && input.token.length > 6;
  const isPasscode = input.token.length === 6 && !input.token.includes(".");

  if (isHashToken) {
    // Re-fetch the session to get qrTokenHash (session was fetched above without it)
    const sessionWithHash = await prisma.workshopSession.findUnique({
      where: { id: input.sessionId },
      select: { qrTokenHash: true }
    });
    const tokenHash = sha256(input.token);
    if (!sessionWithHash?.qrTokenHash || sessionWithHash.qrTokenHash !== tokenHash) {
      throw new ApiError(400, "BAD_REQUEST", "Invalid or expired QR code");
    }
  } else if (isPasscode) {
    // Priority 2: 6-char HMAC passcode (rotating 30s windows)
    const now = Date.now();
    const windowMs = 30 * 1000;
    const currentWindowId = Math.floor(now / windowMs);

    const generatePasscode = (windowId: number) => {
      const hmac = crypto.createHmac("sha256", env.jwtSecret);
      hmac.update(`${input.sessionId}:${windowId}`);
      return hmac.digest("hex").slice(0, 6).toUpperCase();
    };

    const expectedCurrent = generatePasscode(currentWindowId);
    const expectedPrevious = generatePasscode(currentWindowId - 1);
    const provided = input.token.toUpperCase();
    
    const isValid = (
      crypto.timingSafeEqual(Buffer.from(provided.padEnd(6)), Buffer.from(expectedCurrent.padEnd(6))) ||
      crypto.timingSafeEqual(Buffer.from(provided.padEnd(6)), Buffer.from(expectedPrevious.padEnd(6)))
    );
    if (!isValid) {
      throw new ApiError(400, "BAD_REQUEST", "Invalid or expired passcode");
    }
  } else {
    // Priority 3: Short-lived JWT (participant-specific, generated by /sessions/:id/my-attendance-qr)
    try {
      const payload = jwt.verify(input.token, env.jwtSecret) as any;
      if (payload.sessionId !== input.sessionId) throw new Error("Session mismatch");
      if (payload.purpose !== "ATTENDANCE_CHECKIN") throw new Error("Invalid purpose");
    } catch (err) {
      throw new ApiError(400, "BAD_REQUEST", "Invalid or expired QR code");
    }
  }

  // Upsert Attendance
  const attendance = await prisma.attendance.upsert({
    where: { sessionId_registrationId: { sessionId: input.sessionId, registrationId: registration.id } },
    create: {
      sessionId: input.sessionId,
      registrationId: registration.id,
      userId: user.id,
      status: "PRESENT",
      method: "QR",
    },
    update: {
      status: "PRESENT",
      method: "QR",
      recordedAt: new Date(),
    }
  });

  // Create or resume Monitoring Session
  const monitoring = await prisma.attendanceMonitoringSession.upsert({
    where: { attendanceId: attendance.id },
    create: {
      attendanceId: attendance.id,
      sessionId: input.sessionId,
      registrationId: registration.id,
      userId: user.id,
      status: "ACTIVE",
    },
    update: {
      status: "ACTIVE",
      lastVerifiedAt: new Date(),
    }
  });

  emitWorkshopDomainEvent({
    type: "ATTENDANCE_VERIFIED",
    attendanceId: attendance.id,
    sessionId: input.sessionId,
    registrationId: registration.id,
    userId: user.id,
    method: "QR",
    verifiedAt: attendance.recordedAt || new Date()
  });

  return { 
    success: true,
    attendance: {
      status: "PRESENT",
      method: "QR",
      verifiedAt: attendance.recordedAt
    },
    meetingAccess: {
      status: session.meetingUrl ? "UNLOCKED" : "WAITING_FOR_HOST",
      meetingUrl: session.meetingUrl,
    },
    monitoringSession: {
      id: monitoring.id,
      status: monitoring.status
    }
  };
}

export async function heartbeat(user: AuthUser, monitoringId: string) {
  const monitoring = await prisma.attendanceMonitoringSession.findUnique({
    where: { id: monitoringId },
    include: { session: true }
  });
  
  if (!monitoring || monitoring.userId !== user.id) {
    throw new ApiError(404, "NOT_FOUND", "Monitoring session not found");
  }

  if (monitoring.status !== "ACTIVE" || monitoring.session.status !== "LIVE") {
    throw new ApiError(400, "BAD_REQUEST", "Monitoring session is not active");
  }

  return prisma.attendanceMonitoringSession.update({
    where: { id: monitoringId },
    data: { lastVerifiedAt: new Date() }
  });
}

export async function recordEvent(user: AuthUser, input: { monitoringId: string; type: string; clientTime?: string }) {
  const monitoring = await prisma.attendanceMonitoringSession.findUnique({
    where: { id: input.monitoringId },
    include: { session: true }
  });

  if (!monitoring || monitoring.userId !== user.id) {
    throw new ApiError(404, "NOT_FOUND", "Monitoring session not found");
  }

  if (monitoring.status !== "ACTIVE") {
    throw new ApiError(400, "BAD_REQUEST", "Monitoring session is not active");
  }

  return prisma.monitoringEvent.create({
    data: {
      monitoringSessionId: input.monitoringId,
      type: input.type,
      clientTime: input.clientTime ? new Date(input.clientTime) : null,
    }
  });
}

export async function endMonitoring(user: AuthUser, monitoringId: string) {
  const monitoring = await prisma.attendanceMonitoringSession.findUnique({
    where: { id: monitoringId }
  });

  if (!monitoring || monitoring.userId !== user.id) {
    throw new ApiError(404, "NOT_FOUND", "Monitoring session not found");
  }

  return prisma.attendanceMonitoringSession.update({
    where: { id: monitoringId },
    data: {
      status: "COMPLETED",
      terminationReason: "USER_EXITED",
      endedAt: new Date(),
    }
  });
}

export async function getSessionStatus(user: AuthUser, sessionId: string) {
  const session = await prisma.workshopSession.findUnique({ where: { id: sessionId } });
  if (!session) throw new ApiError(404, "NOT_FOUND", "Session not found");

  const registration = await prisma.registration.findUnique({
    where: { workshopId_userId: { workshopId: session.workshopId, userId: user.id } }
  });
  if (!registration || registration.status !== "CONFIRMED") {
    throw new ApiError(403, "FORBIDDEN", "Registration is not confirmed");
  }

  const attendance = await prisma.attendance.findUnique({
    where: { sessionId_registrationId: { sessionId, registrationId: registration.id } }
  });

  const monitoring = attendance ? await prisma.attendanceMonitoringSession.findUnique({
    where: { attendanceId: attendance.id }
  }) : null;

  return {
    status: attendance?.status || "PENDING",
    recordedAt: attendance?.recordedAt,
    monitoringSession: monitoring ? {
      id: monitoring.id,
      status: monitoring.status
    } : null
  };
}
