ALTER TABLE "User" ADD COLUMN "designation" TEXT;
ALTER TYPE "AuditAction" ADD VALUE 'UPDATE_ORGANIZER';
ALTER TYPE "AuditAction" ADD VALUE 'ACTIVATE_ORGANIZER';
ALTER TYPE "AuditAction" ADD VALUE 'SUSPEND_ORGANIZER';
ALTER TYPE "AuditAction" ADD VALUE 'DEACTIVATE_ORGANIZER';
