ALTER TYPE "AuditAction" ADD VALUE 'UPDATE_ORGANIZATION';
ALTER TYPE "AuditAction" ADD VALUE 'ORGANIZATION_STATUS';
ALTER TYPE "AuditAction" ADD VALUE 'CREATE_DEPARTMENT';
ALTER TYPE "AuditAction" ADD VALUE 'UPDATE_DEPARTMENT';
ALTER TYPE "AuditAction" ADD VALUE 'DEPARTMENT_STATUS';
